{
    "openapi": "3.0.1",
    "info": {
        "title": "Spotify getAlbumTracks API",
        "version": "v1",
        "x-apisguru-categories": [
            "media"
        ],
        "x-logo": {
            "url": "https://api.apis.guru/v2/cache/logo/https_logo-core.clearbit.com_spotify.com"
        },
        "x-origin": [{
            "format": "raml",
            "url": "https://raw.githubusercontent.com/spotify/web-api/master/specifications/raml/api.raml",
            "version": "0.8"
        }],
        "x-preferred": true,
        "x-providerName": "spotify.com"
    },
    "servers": [{
        "url": "https://api.spotify.com/v1"
    }],
    "paths": {
        "/albums/{id}/tracks": {
            "get": {
                "description": "[Get an Album's Tracks](https://developer.spotify.com/web-api/get-albums-tracks/)\n",
                "operationId": "getAlbumTracks"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth_2_0_accessCode": {
                "type": "oauth2",
                "description": "Spotify supports OAuth 2.0 for authenticating all API requests.\n",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://accounts.spotify.com/authorize",
                        "tokenUrl": "https://accounts.spotify.com/api/token",
                        "scopes": {
                            "playlist-modify-private": "",
                            "playlist-modify-public": "",
                            "playlist-read-collaborative": "",
                            "playlist-read-private": "",
                            "user-follow-modify": "",
                            "user-follow-read": "",
                            "user-library-modify": "",
                            "user-library-read": "",
                            "user-read-birthdate": "",
                            "user-read-email": "",
                            "user-read-private": ""
                        }
                    }
                }
            },
            "oauth_2_0_implicit": {
                "type": "oauth2",
                "description": "Spotify supports OAuth 2.0 for authenticating all API requests.\n",
                "flows": {
                    "implicit": {
                        "authorizationUrl": "https://accounts.spotify.com/authorize",
                        "scopes": {
                            "playlist-modify-private": "",
                            "playlist-modify-public": "",
                            "playlist-read-collaborative": "",
                            "playlist-read-private": "",
                            "user-follow-modify": "",
                            "user-follow-read": "",
                            "user-library-modify": "",
                            "user-library-read": "",
                            "user-read-birthdate": "",
                            "user-read-email": "",
                            "user-read-private": ""
                        }
                    }
                }
            }
        }
    },
    "x-original-swagger-version": null
}